// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package common

import ()

const (
	ScenarioDefault = "default"

	ScenarioPromptDebug = "prompt_debug"

	ScenarioPromptAsAService = "prompt_as_a_service"

	ScenarioEvalTarget = "eval_target"

	ScenarioEvaluator = "evaluator"
)

type Scenario = string
