// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/apis/observabilitytaskservice"
)

var observabilityTaskClient observabilitytaskservice.Client

// CheckTaskName .
// @router /api/observability/v1/tasks/check_name [GET]
func CheckTaskName(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityTaskClient.CheckTaskName)
}

// CreateTask .
// @router /api/observability/v1/tasks [POST]
func CreateTask(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityTaskClient.CreateTask)
}

// UpdateTask .
// @router /api/observability/v1/tasks/:task_id [PUT]
func UpdateTask(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityTaskClient.UpdateTask)
}

// ListTasks .
// @router /api/observability/v1/tasks/list [POST]
func ListTasks(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityTaskClient.ListTasks)
}

// GetTask .
// @router /api/observability/v1/tasks/:task_id [GET]
func GetTask(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, observabilityTaskClient.GetTask)
}
