// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/prompt/tool_manage/toolmanageservice"
)

var toolManageSvc toolmanageservice.Client

// CreateTool .
// @router /api/prompt/v1/tools [POST]
func CreateTool(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, toolManageSvc.CreateTool)
}

// GetToolDetail .
// @router /api/prompt/v1/tools/:tool_id [GET]
func GetToolDetail(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, toolManageSvc.GetToolDetail)
}

// ListTool .
// @router /api/prompt/v1/tools/list [POST]
func ListTool(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, toolManageSvc.ListTool)
}

// SaveToolDetail .
// @router /api/prompt/v1/tools/:tool_id/drafts/save [POST]
func SaveToolDetail(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, toolManageSvc.SaveToolDetail)
}

// CommitToolDraft .
// @router /api/prompt/v1/tools/:tool_id/drafts/commit [POST]
func CommitToolDraft(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, toolManageSvc.CommitToolDraft)
}

// ListToolCommit .
// @router /api/prompt/v1/tools/:tool_id/commits/list [POST]
func ListToolCommit(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, toolManageSvc.ListToolCommit)
}
