// Code generated by Validator v0.2.6. DO NOT EDIT.

package filter

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *FilterFields) IsValid() error {
	return nil
}
func (p *FilterField) IsValid() error {
	if p.SubFilter != nil {
		if err := p.SubFilter.IsValid(); err != nil {
			return fmt.Errorf("field SubFilter not valid, %w", err)
		}
	}
	return nil
}
func (p *FieldOptions) IsValid() error {
	return nil
}
func (p *TaskFilterFields) IsValid() error {
	return nil
}
func (p *TaskFilterField) IsValid() error {
	if p.SubFilter != nil {
		if err := p.SubFilter.IsValid(); err != nil {
			return fmt.Errorf("field SubFilter not valid, %w", err)
		}
	}
	return nil
}
func (p *SpanFilterFields) IsValid() error {
	if p.Filters != nil {
		if err := p.Filters.IsValid(); err != nil {
			return fmt.Errorf("field Filters not valid, %w", err)
		}
	}
	return nil
}
