// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql (interfaces: IColumnExtractConfigDao)
//
// Generated by this command:
//
//	mockgen -destination=mocks/column_extract_config.go -package=mocks . IColumnExtractConfigDao
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIColumnExtractConfigDao is a mock of IColumnExtractConfigDao interface.
type MockIColumnExtractConfigDao struct {
	ctrl     *gomock.Controller
	recorder *MockIColumnExtractConfigDaoMockRecorder
	isgomock struct{}
}

// MockIColumnExtractConfigDaoMockRecorder is the mock recorder for MockIColumnExtractConfigDao.
type MockIColumnExtractConfigDaoMockRecorder struct {
	mock *MockIColumnExtractConfigDao
}

// NewMockIColumnExtractConfigDao creates a new mock instance.
func NewMockIColumnExtractConfigDao(ctrl *gomock.Controller) *MockIColumnExtractConfigDao {
	mock := &MockIColumnExtractConfigDao{ctrl: ctrl}
	mock.recorder = &MockIColumnExtractConfigDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIColumnExtractConfigDao) EXPECT() *MockIColumnExtractConfigDaoMockRecorder {
	return m.recorder
}

// CreateColumnExtractConfig mocks base method.
func (m *MockIColumnExtractConfigDao) CreateColumnExtractConfig(ctx context.Context, po *model.ObservabilityColumnExtractConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateColumnExtractConfig", ctx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateColumnExtractConfig indicates an expected call of CreateColumnExtractConfig.
func (mr *MockIColumnExtractConfigDaoMockRecorder) CreateColumnExtractConfig(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateColumnExtractConfig", reflect.TypeOf((*MockIColumnExtractConfigDao)(nil).CreateColumnExtractConfig), ctx, po)
}

// GetColumnExtractConfig mocks base method.
func (m *MockIColumnExtractConfigDao) GetColumnExtractConfig(ctx context.Context, workspaceID int64, platformType, spanListType, agentName string) (*model.ObservabilityColumnExtractConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnExtractConfig", ctx, workspaceID, platformType, spanListType, agentName)
	ret0, _ := ret[0].(*model.ObservabilityColumnExtractConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetColumnExtractConfig indicates an expected call of GetColumnExtractConfig.
func (mr *MockIColumnExtractConfigDaoMockRecorder) GetColumnExtractConfig(ctx, workspaceID, platformType, spanListType, agentName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnExtractConfig", reflect.TypeOf((*MockIColumnExtractConfigDao)(nil).GetColumnExtractConfig), ctx, workspaceID, platformType, spanListType, agentName)
}

// UpdateColumnExtractConfig mocks base method.
func (m *MockIColumnExtractConfigDao) UpdateColumnExtractConfig(ctx context.Context, po *model.ObservabilityColumnExtractConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateColumnExtractConfig", ctx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateColumnExtractConfig indicates an expected call of UpdateColumnExtractConfig.
func (mr *MockIColumnExtractConfigDaoMockRecorder) UpdateColumnExtractConfig(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColumnExtractConfig", reflect.TypeOf((*MockIColumnExtractConfigDao)(nil).UpdateColumnExtractConfig), ctx, po)
}

// ListColumnExtractConfigs mocks base method.
func (m *MockIColumnExtractConfigDao) ListColumnExtractConfigs(ctx context.Context, workspaceID int64, platformType, spanListType string) ([]*model.ObservabilityColumnExtractConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListColumnExtractConfigs", ctx, workspaceID, platformType, spanListType)
	ret0, _ := ret[0].([]*model.ObservabilityColumnExtractConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListColumnExtractConfigs indicates an expected call of ListColumnExtractConfigs.
func (mr *MockIColumnExtractConfigDaoMockRecorder) ListColumnExtractConfigs(ctx, workspaceID, platformType, spanListType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListColumnExtractConfigs", reflect.TypeOf((*MockIColumnExtractConfigDao)(nil).ListColumnExtractConfigs), ctx, workspaceID, platformType, spanListType)
}
