// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql (interfaces: ITaskDao)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task.go -package=mocks . ITaskDao
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mysql "github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockITaskDao is a mock of ITaskDao interface.
type MockITaskDao struct {
	ctrl     *gomock.Controller
	recorder *MockITaskDaoMockRecorder
	isgomock struct{}
}

// MockITaskDaoMockRecorder is the mock recorder for MockITaskDao.
type MockITaskDaoMockRecorder struct {
	mock *MockITaskDao
}

// NewMockITaskDao creates a new mock instance.
func NewMockITaskDao(ctrl *gomock.Controller) *MockITaskDao {
	mock := &MockITaskDao{ctrl: ctrl}
	mock.recorder = &MockITaskDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskDao) EXPECT() *MockITaskDaoMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockITaskDao) CreateTask(ctx context.Context, po *model.ObservabilityTask) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, po)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockITaskDaoMockRecorder) CreateTask(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockITaskDao)(nil).CreateTask), ctx, po)
}

// DeleteTask mocks base method.
func (m *MockITaskDao) DeleteTask(ctx context.Context, id, workspaceID int64, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id, workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockITaskDaoMockRecorder) DeleteTask(ctx, id, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockITaskDao)(nil).DeleteTask), ctx, id, workspaceID, userID)
}

// GetObjListWithTask mocks base method.
func (m *MockITaskDao) GetObjListWithTask(ctx context.Context) ([]string, []string, []*model.ObservabilityTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjListWithTask", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].([]*model.ObservabilityTask)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetObjListWithTask indicates an expected call of GetObjListWithTask.
func (mr *MockITaskDaoMockRecorder) GetObjListWithTask(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjListWithTask", reflect.TypeOf((*MockITaskDao)(nil).GetObjListWithTask), ctx)
}

// GetTask mocks base method.
func (m *MockITaskDao) GetTask(ctx context.Context, id int64, workspaceID *int64, userID *string) (*model.ObservabilityTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id, workspaceID, userID)
	ret0, _ := ret[0].(*model.ObservabilityTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockITaskDaoMockRecorder) GetTask(ctx, id, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockITaskDao)(nil).GetTask), ctx, id, workspaceID, userID)
}

// ListTasks mocks base method.
func (m *MockITaskDao) ListTasks(ctx context.Context, param mysql.ListTaskParam) ([]*model.ObservabilityTask, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, param)
	ret0, _ := ret[0].([]*model.ObservabilityTask)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockITaskDaoMockRecorder) ListTasks(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockITaskDao)(nil).ListTasks), ctx, param)
}

// UpdateTask mocks base method.
func (m *MockITaskDao) UpdateTask(ctx context.Context, po *model.ObservabilityTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockITaskDaoMockRecorder) UpdateTask(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockITaskDao)(nil).UpdateTask), ctx, po)
}

// UpdateTaskWithOCC mocks base method.
func (m *MockITaskDao) UpdateTaskWithOCC(ctx context.Context, id, workspaceID int64, updateMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskWithOCC", ctx, id, workspaceID, updateMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskWithOCC indicates an expected call of UpdateTaskWithOCC.
func (mr *MockITaskDaoMockRecorder) UpdateTaskWithOCC(ctx, id, workspaceID, updateMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskWithOCC", reflect.TypeOf((*MockITaskDao)(nil).UpdateTaskWithOCC), ctx, id, workspaceID, updateMap)
}
