// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql (interfaces: ITaskRunDao)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task_run.go -package=mocks . ITaskRunDao
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mysql "github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql"
	model "github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql/gorm_gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockITaskRunDao is a mock of ITaskRunDao interface.
type MockITaskRunDao struct {
	ctrl     *gomock.Controller
	recorder *MockITaskRunDaoMockRecorder
	isgomock struct{}
}

// MockITaskRunDaoMockRecorder is the mock recorder for MockITaskRunDao.
type MockITaskRunDaoMockRecorder struct {
	mock *MockITaskRunDao
}

// NewMockITaskRunDao creates a new mock instance.
func NewMockITaskRunDao(ctrl *gomock.Controller) *MockITaskRunDao {
	mock := &MockITaskRunDao{ctrl: ctrl}
	mock.recorder = &MockITaskRunDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskRunDao) EXPECT() *MockITaskRunDaoMockRecorder {
	return m.recorder
}

// CreateTaskRun mocks base method.
func (m *MockITaskRunDao) CreateTaskRun(ctx context.Context, po *model.ObservabilityTaskRun) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskRun", ctx, po)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskRun indicates an expected call of CreateTaskRun.
func (mr *MockITaskRunDaoMockRecorder) CreateTaskRun(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskRun", reflect.TypeOf((*MockITaskRunDao)(nil).CreateTaskRun), ctx, po)
}

// GetBackfillTaskRun mocks base method.
func (m *MockITaskRunDao) GetBackfillTaskRun(ctx context.Context, workspaceID *int64, taskID int64) (*model.ObservabilityTaskRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBackfillTaskRun", ctx, workspaceID, taskID)
	ret0, _ := ret[0].(*model.ObservabilityTaskRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBackfillTaskRun indicates an expected call of GetBackfillTaskRun.
func (mr *MockITaskRunDaoMockRecorder) GetBackfillTaskRun(ctx, workspaceID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBackfillTaskRun", reflect.TypeOf((*MockITaskRunDao)(nil).GetBackfillTaskRun), ctx, workspaceID, taskID)
}

// GetLatestNewDataTaskRun mocks base method.
func (m *MockITaskRunDao) GetLatestNewDataTaskRun(ctx context.Context, workspaceID *int64, taskID int64) (*model.ObservabilityTaskRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestNewDataTaskRun", ctx, workspaceID, taskID)
	ret0, _ := ret[0].(*model.ObservabilityTaskRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestNewDataTaskRun indicates an expected call of GetLatestNewDataTaskRun.
func (mr *MockITaskRunDaoMockRecorder) GetLatestNewDataTaskRun(ctx, workspaceID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestNewDataTaskRun", reflect.TypeOf((*MockITaskRunDao)(nil).GetLatestNewDataTaskRun), ctx, workspaceID, taskID)
}

// ListTaskRuns mocks base method.
func (m *MockITaskRunDao) ListTaskRuns(ctx context.Context, param mysql.ListTaskRunParam) ([]*model.ObservabilityTaskRun, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskRuns", ctx, param)
	ret0, _ := ret[0].([]*model.ObservabilityTaskRun)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTaskRuns indicates an expected call of ListTaskRuns.
func (mr *MockITaskRunDaoMockRecorder) ListTaskRuns(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskRuns", reflect.TypeOf((*MockITaskRunDao)(nil).ListTaskRuns), ctx, param)
}

// UpdateTaskRun mocks base method.
func (m *MockITaskRunDao) UpdateTaskRun(ctx context.Context, po *model.ObservabilityTaskRun) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskRun", ctx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskRun indicates an expected call of UpdateTaskRun.
func (mr *MockITaskRunDaoMockRecorder) UpdateTaskRun(ctx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskRun", reflect.TypeOf((*MockITaskRunDao)(nil).UpdateTaskRun), ctx, po)
}

// UpdateTaskRunWithOCC mocks base method.
func (m *MockITaskRunDao) UpdateTaskRunWithOCC(ctx context.Context, id, workspaceID int64, updateMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskRunWithOCC", ctx, id, workspaceID, updateMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskRunWithOCC indicates an expected call of UpdateTaskRunWithOCC.
func (mr *MockITaskRunDaoMockRecorder) UpdateTaskRunWithOCC(ctx, id, workspaceID, updateMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskRunWithOCC", reflect.TypeOf((*MockITaskRunDao)(nil).UpdateTaskRunWithOCC), ctx, id, workspaceID, updateMap)
}
