// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/metrics (interfaces: ITraceMetrics)
//
// Generated by this command:
//
//	mockgen -destination=mocks/metrics.go -package=mocks . ITraceMetrics
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockITraceMetrics is a mock of ITraceMetrics interface.
type MockITraceMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockITraceMetricsMockRecorder
	isgomock struct{}
}

// MockITraceMetricsMockRecorder is the mock recorder for MockITraceMetrics.
type MockITraceMetricsMockRecorder struct {
	mock *MockITraceMetrics
}

// NewMockITraceMetrics creates a new mock instance.
func NewMockITraceMetrics(ctrl *gomock.Controller) *MockITraceMetrics {
	mock := &MockITraceMetrics{ctrl: ctrl}
	mock.recorder = &MockITraceMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITraceMetrics) EXPECT() *MockITraceMetricsMockRecorder {
	return m.recorder
}

// EmitGetTrace mocks base method.
func (m *MockITraceMetrics) EmitGetTrace(workspaceId int64, start time.Time, isError bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitGetTrace", workspaceId, start, isError)
}

// EmitGetTrace indicates an expected call of EmitGetTrace.
func (mr *MockITraceMetricsMockRecorder) EmitGetTrace(workspaceId, start, isError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitGetTrace", reflect.TypeOf((*MockITraceMetrics)(nil).EmitGetTrace), workspaceId, start, isError)
}

// EmitListSpans mocks base method.
func (m *MockITraceMetrics) EmitListSpans(workspaceId int64, spanType string, start time.Time, isError bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitListSpans", workspaceId, spanType, start, isError)
}

// EmitListSpans indicates an expected call of EmitListSpans.
func (mr *MockITraceMetricsMockRecorder) EmitListSpans(workspaceId, spanType, start, isError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitListSpans", reflect.TypeOf((*MockITraceMetrics)(nil).EmitListSpans), workspaceId, spanType, start, isError)
}

// EmitListSpansOapi mocks base method.
func (m *MockITraceMetrics) EmitListSpansOapi(workspaceId int64, platformType, spanType string, spanSize int64, errorCode int, start time.Time, isError bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitListSpansOapi", workspaceId, platformType, spanType, spanSize, errorCode, start, isError)
}

// EmitListSpansOapi indicates an expected call of EmitListSpansOapi.
func (mr *MockITraceMetricsMockRecorder) EmitListSpansOapi(workspaceId, platformType, spanType, spanSize, errorCode, start, isError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitListSpansOapi", reflect.TypeOf((*MockITraceMetrics)(nil).EmitListSpansOapi), workspaceId, platformType, spanType, spanSize, errorCode, start, isError)
}

// EmitListTracesOapi mocks base method.
func (m *MockITraceMetrics) EmitListTracesOapi(workspaceId int64, errorCode int, start time.Time, isError bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitListTracesOapi", workspaceId, errorCode, start, isError)
}

// EmitListTracesOapi indicates an expected call of EmitListTracesOapi.
func (mr *MockITraceMetricsMockRecorder) EmitListTracesOapi(workspaceId, errorCode, start, isError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitListTracesOapi", reflect.TypeOf((*MockITraceMetrics)(nil).EmitListTracesOapi), workspaceId, errorCode, start, isError)
}

// EmitSearchTraceOapi mocks base method.
func (m *MockITraceMetrics) EmitSearchTraceOapi(workspaceId int64, platformType string, spanSize int64, errorCode int, start time.Time, isError bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitSearchTraceOapi", workspaceId, platformType, spanSize, errorCode, start, isError)
}

// EmitSearchTraceOapi indicates an expected call of EmitSearchTraceOapi.
func (mr *MockITraceMetricsMockRecorder) EmitSearchTraceOapi(workspaceId, platformType, spanSize, errorCode, start, isError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitSearchTraceOapi", reflect.TypeOf((*MockITraceMetrics)(nil).EmitSearchTraceOapi), workspaceId, platformType, spanSize, errorCode, start, isError)
}
