// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/prompt/domain/service (interfaces: IContextReorganizer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/context_reorganizer.go -package=mocks . IContextReorganizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/entity"
	service "github.com/coze-dev/coze-loop/backend/modules/prompt/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockIContextReorganizer is a mock of IContextReorganizer interface.
type MockIContextReorganizer struct {
	ctrl     *gomock.Controller
	recorder *MockIContextReorganizerMockRecorder
	isgomock struct{}
}

// MockIContextReorganizerMockRecorder is the mock recorder for MockIContextReorganizer.
type MockIContextReorganizerMockRecorder struct {
	mock *MockIContextReorganizer
}

// NewMockIContextReorganizer creates a new mock instance.
func NewMockIContextReorganizer(ctrl *gomock.Controller) *MockIContextReorganizer {
	mock := &MockIContextReorganizer{ctrl: ctrl}
	mock.recorder = &MockIContextReorganizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContextReorganizer) EXPECT() *MockIContextReorganizerMockRecorder {
	return m.recorder
}

// ReorganizeContexts mocks base method.
func (m *MockIContextReorganizer) ReorganizeContexts(ctx context.Context, param service.ReorganizeContextParam) ([]*entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorganizeContexts", ctx, param)
	ret0, _ := ret[0].([]*entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorganizeContexts indicates an expected call of ReorganizeContexts.
func (mr *MockIContextReorganizerMockRecorder) ReorganizeContexts(ctx, param any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorganizeContexts", reflect.TypeOf((*MockIContextReorganizer)(nil).ReorganizeContexts), ctx, param)
}
