// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNamePromptCommitLabelMapping = "prompt_commit_label_mapping"

// PromptCommitLabelMapping Prompt提交版本和Label关联表
type PromptCommitLabelMapping struct {
	ID            int64                 `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                                    // 主键ID
	SpaceID       int64                 `gorm:"column:space_id;type:bigint(20) unsigned;not null;comment:空间ID" json:"space_id"`                                                                                                             // 空间ID
	PromptID      int64                 `gorm:"column:prompt_id;type:bigint(20) unsigned;not null;uniqueIndex:uniq_prompt_id_label_key_deleted_at,priority:1;index:idx_prompt_id_version,priority:1;comment:Prompt ID" json:"prompt_id"`    // Prompt ID
	LabelKey      string                `gorm:"column:label_key;type:varchar(128);not null;uniqueIndex:uniq_prompt_id_label_key_deleted_at,priority:2;comment:Label唯一标识" json:"label_key"`                                                  // Label唯一标识
	PromptVersion string                `gorm:"column:prompt_version;type:varchar(128);not null;index:idx_prompt_id_version,priority:2;comment:Prompt版本" json:"prompt_version"`                                                             // Prompt版本
	CreatedBy     string                `gorm:"column:created_by;type:varchar(128);not null;comment:创建人" json:"created_by"`                                                                                                                 // 创建人
	CreatedAt     time.Time             `gorm:"column:created_at;type:datetime;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                          // 创建时间
	UpdatedBy     string                `gorm:"column:updated_by;type:varchar(128);not null;comment:更新人" json:"updated_by"`                                                                                                                 // 更新人
	UpdatedAt     time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                                          // 更新时间
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint(20);not null;uniqueIndex:uniq_prompt_id_label_key_deleted_at,priority:3;column:deleted_at;not null;default:0;softDelete:milli;comment:删除时间" json:"deleted_at"` // 删除时间
}

// TableName PromptCommitLabelMapping's table name
func (*PromptCommitLabelMapping) TableName() string {
	return TableNamePromptCommitLabelMapping
}
