// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNamePromptLabel = "prompt_label"

// PromptLabel Prompt Label表
type PromptLabel struct {
	ID        int64                 `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                                        // 主键ID
	SpaceID   int64                 `gorm:"column:space_id;type:bigint(20) unsigned;not null;uniqueIndex:uniq_space_id_label_key,priority:1;comment:空间ID" json:"space_id"`                                                  // 空间ID
	LabelKey  string                `gorm:"column:label_key;type:varchar(128);not null;uniqueIndex:uniq_space_id_label_key,priority:2;comment:Label唯一标识" json:"label_key"`                                                  // Label唯一标识
	CreatedBy string                `gorm:"column:created_by;type:varchar(128);not null;comment:创建人" json:"created_by"`                                                                                                     // 创建人
	CreatedAt time.Time             `gorm:"column:created_at;type:datetime;not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                              // 创建时间
	UpdatedBy string                `gorm:"column:updated_by;type:varchar(128);not null;comment:更新人" json:"updated_by"`                                                                                                     // 更新人
	UpdatedAt time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                              // 更新时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint(20);not null;uniqueIndex:uniq_space_id_label_key,priority:3;column:deleted_at;not null;default:0;softDelete:milli;comment:删除时间" json:"deleted_at"` // 删除时间
}

// TableName PromptLabel's table name
func (*PromptLabel) TableName() string {
	return TableNamePromptLabel
}
