// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/mysql/gorm_gen/model"
)

func newObservabilityColumnExtractConfig(db *gorm.DB, opts ...gen.DOOption) observabilityColumnExtractConfig {
	_observabilityColumnExtractConfig := observabilityColumnExtractConfig{}

	_observabilityColumnExtractConfig.observabilityColumnExtractConfigDo.UseDB(db, opts...)
	_observabilityColumnExtractConfig.observabilityColumnExtractConfigDo.UseModel(&model.ObservabilityColumnExtractConfig{})

	tableName := _observabilityColumnExtractConfig.observabilityColumnExtractConfigDo.TableName()
	_observabilityColumnExtractConfig.ALL = field.NewAsterisk(tableName)
	_observabilityColumnExtractConfig.ID = field.NewInt64(tableName, "id")
	_observabilityColumnExtractConfig.WorkspaceID = field.NewInt64(tableName, "workspace_id")
	_observabilityColumnExtractConfig.PlatformType = field.NewString(tableName, "platform_type")
	_observabilityColumnExtractConfig.SpanListType = field.NewString(tableName, "span_list_type")
	_observabilityColumnExtractConfig.AgentName = field.NewString(tableName, "agent_name")
	_observabilityColumnExtractConfig.Config = field.NewString(tableName, "config")
	_observabilityColumnExtractConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_observabilityColumnExtractConfig.CreatedBy = field.NewString(tableName, "created_by")
	_observabilityColumnExtractConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_observabilityColumnExtractConfig.UpdatedBy = field.NewString(tableName, "updated_by")
	_observabilityColumnExtractConfig.IsDeleted = field.NewBool(tableName, "is_deleted")
	_observabilityColumnExtractConfig.DeletedAt = field.NewField(tableName, "deleted_at")
	_observabilityColumnExtractConfig.DeletedBy = field.NewString(tableName, "deleted_by")

	_observabilityColumnExtractConfig.fillFieldMap()

	return _observabilityColumnExtractConfig
}

// observabilityColumnExtractConfig 列提取配置
type observabilityColumnExtractConfig struct {
	observabilityColumnExtractConfigDo observabilityColumnExtractConfigDo

	ALL          field.Asterisk
	ID           field.Int64  // 主键ID
	WorkspaceID  field.Int64  // 空间 ID
	PlatformType field.String // 数据来源
	SpanListType field.String // 列表信息
	AgentName    field.String // agent名称
	Config       field.String // 提取规则配置JSON
	CreatedAt    field.Time   // 创建时间
	CreatedBy    field.String // 创建人
	UpdatedAt    field.Time   // 修改时间
	UpdatedBy    field.String // 修改人
	IsDeleted    field.Bool   // 是否删除, 0 表示未删除, 1 表示已删除
	DeletedAt    field.Field  // 删除时间
	DeletedBy    field.String // 删除人

	fieldMap map[string]field.Expr
}

func (o observabilityColumnExtractConfig) Table(newTableName string) *observabilityColumnExtractConfig {
	o.observabilityColumnExtractConfigDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o observabilityColumnExtractConfig) As(alias string) *observabilityColumnExtractConfig {
	o.observabilityColumnExtractConfigDo.DO = *(o.observabilityColumnExtractConfigDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *observabilityColumnExtractConfig) updateTableName(table string) *observabilityColumnExtractConfig {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.WorkspaceID = field.NewInt64(table, "workspace_id")
	o.PlatformType = field.NewString(table, "platform_type")
	o.SpanListType = field.NewString(table, "span_list_type")
	o.AgentName = field.NewString(table, "agent_name")
	o.Config = field.NewString(table, "config")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.CreatedBy = field.NewString(table, "created_by")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.UpdatedBy = field.NewString(table, "updated_by")
	o.IsDeleted = field.NewBool(table, "is_deleted")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.DeletedBy = field.NewString(table, "deleted_by")

	o.fillFieldMap()

	return o
}

func (o *observabilityColumnExtractConfig) WithContext(ctx context.Context) *observabilityColumnExtractConfigDo {
	return o.observabilityColumnExtractConfigDo.WithContext(ctx)
}

func (o observabilityColumnExtractConfig) TableName() string {
	return o.observabilityColumnExtractConfigDo.TableName()
}

func (o observabilityColumnExtractConfig) Alias() string {
	return o.observabilityColumnExtractConfigDo.Alias()
}

func (o observabilityColumnExtractConfig) Columns(cols ...field.Expr) gen.Columns {
	return o.observabilityColumnExtractConfigDo.Columns(cols...)
}

func (o *observabilityColumnExtractConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *observabilityColumnExtractConfig) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 13)
	o.fieldMap["id"] = o.ID
	o.fieldMap["workspace_id"] = o.WorkspaceID
	o.fieldMap["platform_type"] = o.PlatformType
	o.fieldMap["span_list_type"] = o.SpanListType
	o.fieldMap["agent_name"] = o.AgentName
	o.fieldMap["config"] = o.Config
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["created_by"] = o.CreatedBy
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["updated_by"] = o.UpdatedBy
	o.fieldMap["is_deleted"] = o.IsDeleted
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["deleted_by"] = o.DeletedBy
}

func (o observabilityColumnExtractConfig) clone(db *gorm.DB) observabilityColumnExtractConfig {
	o.observabilityColumnExtractConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o observabilityColumnExtractConfig) replaceDB(db *gorm.DB) observabilityColumnExtractConfig {
	o.observabilityColumnExtractConfigDo.ReplaceDB(db)
	return o
}

type observabilityColumnExtractConfigDo struct{ gen.DO }

func (o observabilityColumnExtractConfigDo) Debug() *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Debug())
}

func (o observabilityColumnExtractConfigDo) WithContext(ctx context.Context) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o observabilityColumnExtractConfigDo) ReadDB() *observabilityColumnExtractConfigDo {
	return o.Clauses(dbresolver.Read)
}

func (o observabilityColumnExtractConfigDo) WriteDB() *observabilityColumnExtractConfigDo {
	return o.Clauses(dbresolver.Write)
}

func (o observabilityColumnExtractConfigDo) Session(config *gorm.Session) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Session(config))
}

func (o observabilityColumnExtractConfigDo) Clauses(conds ...clause.Expression) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o observabilityColumnExtractConfigDo) Returning(value interface{}, columns ...string) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o observabilityColumnExtractConfigDo) Not(conds ...gen.Condition) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o observabilityColumnExtractConfigDo) Or(conds ...gen.Condition) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o observabilityColumnExtractConfigDo) Select(conds ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o observabilityColumnExtractConfigDo) Where(conds ...gen.Condition) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o observabilityColumnExtractConfigDo) Order(conds ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o observabilityColumnExtractConfigDo) Distinct(cols ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o observabilityColumnExtractConfigDo) Omit(cols ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o observabilityColumnExtractConfigDo) Join(table schema.Tabler, on ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o observabilityColumnExtractConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o observabilityColumnExtractConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o observabilityColumnExtractConfigDo) Group(cols ...field.Expr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o observabilityColumnExtractConfigDo) Having(conds ...gen.Condition) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o observabilityColumnExtractConfigDo) Limit(limit int) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o observabilityColumnExtractConfigDo) Offset(offset int) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o observabilityColumnExtractConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o observabilityColumnExtractConfigDo) Unscoped() *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Unscoped())
}

func (o observabilityColumnExtractConfigDo) Create(values ...*model.ObservabilityColumnExtractConfig) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o observabilityColumnExtractConfigDo) CreateInBatches(values []*model.ObservabilityColumnExtractConfig, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o observabilityColumnExtractConfigDo) Save(values ...*model.ObservabilityColumnExtractConfig) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o observabilityColumnExtractConfigDo) First() (*model.ObservabilityColumnExtractConfig, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityColumnExtractConfig), nil
	}
}

func (o observabilityColumnExtractConfigDo) Take() (*model.ObservabilityColumnExtractConfig, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityColumnExtractConfig), nil
	}
}

func (o observabilityColumnExtractConfigDo) Last() (*model.ObservabilityColumnExtractConfig, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityColumnExtractConfig), nil
	}
}

func (o observabilityColumnExtractConfigDo) Find() ([]*model.ObservabilityColumnExtractConfig, error) {
	result, err := o.DO.Find()
	return result.([]*model.ObservabilityColumnExtractConfig), err
}

func (o observabilityColumnExtractConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ObservabilityColumnExtractConfig, err error) {
	buf := make([]*model.ObservabilityColumnExtractConfig, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o observabilityColumnExtractConfigDo) FindInBatches(result *[]*model.ObservabilityColumnExtractConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o observabilityColumnExtractConfigDo) Attrs(attrs ...field.AssignExpr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o observabilityColumnExtractConfigDo) Assign(attrs ...field.AssignExpr) *observabilityColumnExtractConfigDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o observabilityColumnExtractConfigDo) Joins(fields ...field.RelationField) *observabilityColumnExtractConfigDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o observabilityColumnExtractConfigDo) Preload(fields ...field.RelationField) *observabilityColumnExtractConfigDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o observabilityColumnExtractConfigDo) FirstOrInit() (*model.ObservabilityColumnExtractConfig, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityColumnExtractConfig), nil
	}
}

func (o observabilityColumnExtractConfigDo) FirstOrCreate() (*model.ObservabilityColumnExtractConfig, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ObservabilityColumnExtractConfig), nil
	}
}

func (o observabilityColumnExtractConfigDo) FindByPage(offset int, limit int) (result []*model.ObservabilityColumnExtractConfig, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o observabilityColumnExtractConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o observabilityColumnExtractConfigDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o observabilityColumnExtractConfigDo) Delete(models ...*model.ObservabilityColumnExtractConfig) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *observabilityColumnExtractConfigDo) withDO(do gen.Dao) *observabilityColumnExtractConfigDo {
	o.DO = *do.(*gen.DO)
	return o
}
