// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/task (interfaces: IWorkflowProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task_hook.go -package=mocks . IWorkflowProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	task "github.com/coze-dev/coze-loop/backend/modules/observability/domain/component/task"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkflowProvider is a mock of IWorkflowProvider interface.
type MockIWorkflowProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowProviderMockRecorder
	isgomock struct{}
}

// MockIWorkflowProviderMockRecorder is the mock recorder for MockIWorkflowProvider.
type MockIWorkflowProviderMockRecorder struct {
	mock *MockIWorkflowProvider
}

// NewMockIWorkflowProvider creates a new mock instance.
func NewMockIWorkflowProvider(ctrl *gomock.Controller) *MockIWorkflowProvider {
	mock := &MockIWorkflowProvider{ctrl: ctrl}
	mock.recorder = &MockIWorkflowProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowProvider) EXPECT() *MockIWorkflowProviderMockRecorder {
	return m.recorder
}

// WorkflowCallback mocks base method.
func (m *MockIWorkflowProvider) WorkflowCallback(ctx context.Context, event *task.WorkflowCallbackParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowCallback", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkflowCallback indicates an expected call of WorkflowCallback.
func (mr *MockIWorkflowProviderMockRecorder) WorkflowCallback(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowCallback", reflect.TypeOf((*MockIWorkflowProvider)(nil).WorkflowCallback), ctx, event)
}
