// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/auth_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
