// Code generated by cozeloop. DO NOT EDIT.
package loingestion // import github.com/coze-dev/coze-loop/backend/loingestion

import (
	"context"

	"github.com/cloudwego/kitex/pkg/endpoint"
	"github.com/cloudwego/kitex/pkg/rpcinfo"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/observability/ingestion"
)

type LocalIngestionService struct {
	impl ingestion.IngestionService // the service implementation
	mds  endpoint.Middleware
}

func NewLocalIngestionService(impl ingestion.IngestionService, mds ...endpoint.Middleware) *LocalIngestionService {
	return &LocalIngestionService{
		impl: impl,
		mds:  endpoint.Chain(mds...),
	}
}

func (l *LocalIngestionService) injectRPCInfo(ctx context.Context, method string) context.Context {
	rpcStats := rpcinfo.AsMutableRPCStats(rpcinfo.NewRPCStats())
	ri := rpcinfo.NewRPCInfo(
		rpcinfo.NewEndpointInfo("IngestionService", method, nil, nil),
		rpcinfo.NewEndpointInfo("IngestionService", method, nil, nil),
		rpcinfo.NewServerInvocation(),
		nil,
		rpcStats.ImmutableView(),
	)
	return rpcinfo.NewCtxWithRPCInfo(ctx, ri)
}
