// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/redis/dao (interfaces: ITaskDAO)
//
// Generated by this command:
//
//	mockgen -destination=mocks/Task_dao.go -package=mocks . ITaskDAO
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/coze-dev/coze-loop/backend/modules/observability/domain/task/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockITaskDAO is a mock of ITaskDAO interface.
type MockITaskDAO struct {
	ctrl     *gomock.Controller
	recorder *MockITaskDAOMockRecorder
	isgomock struct{}
}

// MockITaskDAOMockRecorder is the mock recorder for MockITaskDAO.
type MockITaskDAOMockRecorder struct {
	mock *MockITaskDAO
}

// NewMockITaskDAO creates a new mock instance.
func NewMockITaskDAO(ctrl *gomock.Controller) *MockITaskDAO {
	mock := &MockITaskDAO{ctrl: ctrl}
	mock.recorder = &MockITaskDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskDAO) EXPECT() *MockITaskDAOMockRecorder {
	return m.recorder
}

// AddNonFinalTask mocks base method.
func (m *MockITaskDAO) AddNonFinalTask(ctx context.Context, spaceID string, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNonFinalTask", ctx, spaceID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNonFinalTask indicates an expected call of AddNonFinalTask.
func (mr *MockITaskDAOMockRecorder) AddNonFinalTask(ctx, spaceID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNonFinalTask", reflect.TypeOf((*MockITaskDAO)(nil).AddNonFinalTask), ctx, spaceID, taskID)
}

// DecrTaskCount mocks base method.
func (m *MockITaskDAO) DecrTaskCount(ctx context.Context, taskID int64, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrTaskCount", ctx, taskID, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrTaskCount indicates an expected call of DecrTaskCount.
func (mr *MockITaskDAOMockRecorder) DecrTaskCount(ctx, taskID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrTaskCount", reflect.TypeOf((*MockITaskDAO)(nil).DecrTaskCount), ctx, taskID, ttl)
}

// DecrTaskRunCount mocks base method.
func (m *MockITaskDAO) DecrTaskRunCount(ctx context.Context, taskID, taskRunID int64, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrTaskRunCount", ctx, taskID, taskRunID, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrTaskRunCount indicates an expected call of DecrTaskRunCount.
func (mr *MockITaskDAOMockRecorder) DecrTaskRunCount(ctx, taskID, taskRunID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrTaskRunCount", reflect.TypeOf((*MockITaskDAO)(nil).DecrTaskRunCount), ctx, taskID, taskRunID, ttl)
}

// GetTask mocks base method.
func (m *MockITaskDAO) GetTask(ctx context.Context, taskID int64) (*entity.ObservabilityTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, taskID)
	ret0, _ := ret[0].(*entity.ObservabilityTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockITaskDAOMockRecorder) GetTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockITaskDAO)(nil).GetTask), ctx, taskID)
}

// GetTaskCount mocks base method.
func (m *MockITaskDAO) GetTaskCount(ctx context.Context, taskID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskCount", ctx, taskID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskCount indicates an expected call of GetTaskCount.
func (mr *MockITaskDAOMockRecorder) GetTaskCount(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskCount", reflect.TypeOf((*MockITaskDAO)(nil).GetTaskCount), ctx, taskID)
}

// GetTaskRunCount mocks base method.
func (m *MockITaskDAO) GetTaskRunCount(ctx context.Context, taskID, taskRunID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskRunCount", ctx, taskID, taskRunID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskRunCount indicates an expected call of GetTaskRunCount.
func (mr *MockITaskDAOMockRecorder) GetTaskRunCount(ctx, taskID, taskRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskRunCount", reflect.TypeOf((*MockITaskDAO)(nil).GetTaskRunCount), ctx, taskID, taskRunID)
}

// IncrTaskCount mocks base method.
func (m *MockITaskDAO) IncrTaskCount(ctx context.Context, taskID int64, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrTaskCount", ctx, taskID, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrTaskCount indicates an expected call of IncrTaskCount.
func (mr *MockITaskDAOMockRecorder) IncrTaskCount(ctx, taskID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrTaskCount", reflect.TypeOf((*MockITaskDAO)(nil).IncrTaskCount), ctx, taskID, ttl)
}

// IncrTaskRunCount mocks base method.
func (m *MockITaskDAO) IncrTaskRunCount(ctx context.Context, taskID, taskRunID int64, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrTaskRunCount", ctx, taskID, taskRunID, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrTaskRunCount indicates an expected call of IncrTaskRunCount.
func (mr *MockITaskDAOMockRecorder) IncrTaskRunCount(ctx, taskID, taskRunID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrTaskRunCount", reflect.TypeOf((*MockITaskDAO)(nil).IncrTaskRunCount), ctx, taskID, taskRunID, ttl)
}

// ListNonFinalTask mocks base method.
func (m *MockITaskDAO) ListNonFinalTask(ctx context.Context, spaceID string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNonFinalTask", ctx, spaceID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNonFinalTask indicates an expected call of ListNonFinalTask.
func (mr *MockITaskDAOMockRecorder) ListNonFinalTask(ctx, spaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNonFinalTask", reflect.TypeOf((*MockITaskDAO)(nil).ListNonFinalTask), ctx, spaceID)
}

// RemoveNonFinalTask mocks base method.
func (m *MockITaskDAO) RemoveNonFinalTask(ctx context.Context, spaceID string, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNonFinalTask", ctx, spaceID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNonFinalTask indicates an expected call of RemoveNonFinalTask.
func (mr *MockITaskDAOMockRecorder) RemoveNonFinalTask(ctx, spaceID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNonFinalTask", reflect.TypeOf((*MockITaskDAO)(nil).RemoveNonFinalTask), ctx, spaceID, taskID)
}

// SetTask mocks base method.
func (m *MockITaskDAO) SetTask(ctx context.Context, task *entity.ObservabilityTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTask indicates an expected call of SetTask.
func (mr *MockITaskDAOMockRecorder) SetTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTask", reflect.TypeOf((*MockITaskDAO)(nil).SetTask), ctx, task)
}
