// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/infra/repo/redis/dao (interfaces: ITaskRunDAO)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task_run_dao.go -package=mocks . ITaskRunDAO
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockITaskRunDAO is a mock of ITaskRunDAO interface.
type MockITaskRunDAO struct {
	ctrl     *gomock.Controller
	recorder *MockITaskRunDAOMockRecorder
	isgomock struct{}
}

// MockITaskRunDAOMockRecorder is the mock recorder for MockITaskRunDAO.
type MockITaskRunDAOMockRecorder struct {
	mock *MockITaskRunDAO
}

// NewMockITaskRunDAO creates a new mock instance.
func NewMockITaskRunDAO(ctrl *gomock.Controller) *MockITaskRunDAO {
	mock := &MockITaskRunDAO{ctrl: ctrl}
	mock.recorder = &MockITaskRunDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskRunDAO) EXPECT() *MockITaskRunDAOMockRecorder {
	return m.recorder
}

// DecrTaskRunSuccessCount mocks base method.
func (m *MockITaskRunDAO) DecrTaskRunSuccessCount(ctx context.Context, taskID, taskRunID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrTaskRunSuccessCount", ctx, taskID, taskRunID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrTaskRunSuccessCount indicates an expected call of DecrTaskRunSuccessCount.
func (mr *MockITaskRunDAOMockRecorder) DecrTaskRunSuccessCount(ctx, taskID, taskRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrTaskRunSuccessCount", reflect.TypeOf((*MockITaskRunDAO)(nil).DecrTaskRunSuccessCount), ctx, taskID, taskRunID)
}

// GetTaskRunFailCount mocks base method.
func (m *MockITaskRunDAO) GetTaskRunFailCount(ctx context.Context, taskID, taskRunID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskRunFailCount", ctx, taskID, taskRunID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskRunFailCount indicates an expected call of GetTaskRunFailCount.
func (mr *MockITaskRunDAOMockRecorder) GetTaskRunFailCount(ctx, taskID, taskRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskRunFailCount", reflect.TypeOf((*MockITaskRunDAO)(nil).GetTaskRunFailCount), ctx, taskID, taskRunID)
}

// GetTaskRunSuccessCount mocks base method.
func (m *MockITaskRunDAO) GetTaskRunSuccessCount(ctx context.Context, taskID, taskRunID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskRunSuccessCount", ctx, taskID, taskRunID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskRunSuccessCount indicates an expected call of GetTaskRunSuccessCount.
func (mr *MockITaskRunDAOMockRecorder) GetTaskRunSuccessCount(ctx, taskID, taskRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskRunSuccessCount", reflect.TypeOf((*MockITaskRunDAO)(nil).GetTaskRunSuccessCount), ctx, taskID, taskRunID)
}

// IncrTaskRunFailCount mocks base method.
func (m *MockITaskRunDAO) IncrTaskRunFailCount(ctx context.Context, taskID, taskRunID int64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrTaskRunFailCount", ctx, taskID, taskRunID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrTaskRunFailCount indicates an expected call of IncrTaskRunFailCount.
func (mr *MockITaskRunDAOMockRecorder) IncrTaskRunFailCount(ctx, taskID, taskRunID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrTaskRunFailCount", reflect.TypeOf((*MockITaskRunDAO)(nil).IncrTaskRunFailCount), ctx, taskID, taskRunID, ttl)
}

// IncrTaskRunSuccessCount mocks base method.
func (m *MockITaskRunDAO) IncrTaskRunSuccessCount(ctx context.Context, taskID, taskRunID int64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrTaskRunSuccessCount", ctx, taskID, taskRunID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrTaskRunSuccessCount indicates an expected call of IncrTaskRunSuccessCount.
func (mr *MockITaskRunDAOMockRecorder) IncrTaskRunSuccessCount(ctx, taskID, taskRunID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrTaskRunSuccessCount", reflect.TypeOf((*MockITaskRunDAO)(nil).IncrTaskRunSuccessCount), ctx, taskID, taskRunID, ttl)
}
