// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/service (interfaces: IngestionService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/ingestion.go -package=mocks . IngestionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIngestionService is a mock of IngestionService interface.
type MockIngestionService struct {
	ctrl     *gomock.Controller
	recorder *MockIngestionServiceMockRecorder
}

// MockIngestionServiceMockRecorder is the mock recorder for MockIngestionService.
type MockIngestionServiceMockRecorder struct {
	mock *MockIngestionService
}

// NewMockIngestionService creates a new mock instance.
func NewMockIngestionService(ctrl *gomock.Controller) *MockIngestionService {
	mock := &MockIngestionService{ctrl: ctrl}
	mock.recorder = &MockIngestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestionService) EXPECT() *MockIngestionServiceMockRecorder {
	return m.recorder
}

// RunAsync mocks base method.
func (m *MockIngestionService) RunAsync(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunAsync", arg0)
}

// RunAsync indicates an expected call of RunAsync.
func (mr *MockIngestionServiceMockRecorder) RunAsync(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAsync", reflect.TypeOf((*MockIngestionService)(nil).RunAsync), arg0)
}

// RunSync mocks base method.
func (m *MockIngestionService) RunSync(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSync", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunSync indicates an expected call of RunSync.
func (mr *MockIngestionServiceMockRecorder) RunSync(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSync", reflect.TypeOf((*MockIngestionService)(nil).RunSync), arg0)
}
