// Code generated by Validator v0.2.6. DO NOT EDIT.

package openapi

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *BatchGetPromptByPromptKeyRequest) IsValid() error {
	if p.Base != nil {
		if err := p.Base.IsValid(); err != nil {
			return fmt.Errorf("field Base not valid, %w", err)
		}
	}
	return nil
}
func (p *BatchGetPromptByPromptKeyResponse) IsValid() error {
	if p.Data != nil {
		if err := p.Data.IsValid(); err != nil {
			return fmt.Errorf("field Data not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *ExecuteRequest) IsValid() error {
	if p.PromptIdentifier != nil {
		if err := p.PromptIdentifier.IsValid(); err != nil {
			return fmt.Errorf("field PromptIdentifier not valid, %w", err)
		}
	}
	if p.CustomToolCallConfig != nil {
		if err := p.CustomToolCallConfig.IsValid(); err != nil {
			return fmt.Errorf("field CustomToolCallConfig not valid, %w", err)
		}
	}
	if p.CustomModelConfig != nil {
		if err := p.CustomModelConfig.IsValid(); err != nil {
			return fmt.Errorf("field CustomModelConfig not valid, %w", err)
		}
	}
	if p.ResponseAPIConfig != nil {
		if err := p.ResponseAPIConfig.IsValid(); err != nil {
			return fmt.Errorf("field ResponseAPIConfig not valid, %w", err)
		}
	}
	if p.CustomToolConfig != nil {
		if err := p.CustomToolConfig.IsValid(); err != nil {
			return fmt.Errorf("field CustomToolConfig not valid, %w", err)
		}
	}
	if p.Base != nil {
		if err := p.Base.IsValid(); err != nil {
			return fmt.Errorf("field Base not valid, %w", err)
		}
	}
	return nil
}
func (p *ExecuteResponse) IsValid() error {
	if p.Data != nil {
		if err := p.Data.IsValid(); err != nil {
			return fmt.Errorf("field Data not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *ExecuteStreamingResponse) IsValid() error {
	if p.Data != nil {
		if err := p.Data.IsValid(); err != nil {
			return fmt.Errorf("field Data not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
func (p *ListPromptBasicRequest) IsValid() error {
	if p.PageNumber != nil {
		if *p.PageNumber <= int32(0) {
			return fmt.Errorf("field PageNumber gt rule failed, current value: %v", *p.PageNumber)
		}
	}
	if p.PageSize != nil {
		if *p.PageSize <= int32(0) {
			return fmt.Errorf("field PageSize gt rule failed, current value: %v", *p.PageSize)
		}
		if *p.PageSize > int32(200) {
			return fmt.Errorf("field PageSize le rule failed, current value: %v", *p.PageSize)
		}
	}
	if p.Base != nil {
		if err := p.Base.IsValid(); err != nil {
			return fmt.Errorf("field Base not valid, %w", err)
		}
	}
	return nil
}
func (p *ListPromptBasicResponse) IsValid() error {
	if p.Data != nil {
		if err := p.Data.IsValid(); err != nil {
			return fmt.Errorf("field Data not valid, %w", err)
		}
	}
	if p.BaseResp != nil {
		if err := p.BaseResp.IsValid(); err != nil {
			return fmt.Errorf("field BaseResp not valid, %w", err)
		}
	}
	return nil
}
