// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/llm/domain/service (interfaces: IManage)
//
// Generated by this command:
//
//	mockgen -destination=mocks/manage.go -package=mocks . IManage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/llm/domain/entity"
	service "github.com/coze-dev/coze-loop/backend/modules/llm/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockIManage is a mock of IManage interface.
type MockIManage struct {
	ctrl     *gomock.Controller
	recorder *MockIManageMockRecorder
	isgomock struct{}
}

// MockIManageMockRecorder is the mock recorder for MockIManage.
type MockIManageMockRecorder struct {
	mock *MockIManage
}

// NewMockIManage creates a new mock instance.
func NewMockIManage(ctrl *gomock.Controller) *MockIManage {
	mock := &MockIManage{ctrl: ctrl}
	mock.recorder = &MockIManageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIManage) EXPECT() *MockIManageMockRecorder {
	return m.recorder
}

// GetModelByID mocks base method.
func (m *MockIManage) GetModelByID(ctx context.Context, id int64) (*entity.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByID", ctx, id)
	ret0, _ := ret[0].(*entity.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByID indicates an expected call of GetModelByID.
func (mr *MockIManageMockRecorder) GetModelByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByID", reflect.TypeOf((*MockIManage)(nil).GetModelByID), ctx, id)
}

// GetModelByKey mocks base method.
func (m *MockIManage) GetModelByKey(ctx context.Context, workspaceID int64, key string) (*entity.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByKey", ctx, workspaceID, key)
	ret0, _ := ret[0].(*entity.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByKey indicates an expected call of GetModelByKey.
func (mr *MockIManageMockRecorder) GetModelByKey(ctx, workspaceID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByKey", reflect.TypeOf((*MockIManage)(nil).GetModelByKey), ctx, workspaceID, key)
}

// ResolveByKeyOrID mocks base method.
func (m *MockIManage) ResolveByKeyOrID(ctx context.Context, ref service.KeyOrIDRef) (*entity.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveByKeyOrID", ctx, ref)
	ret0, _ := ret[0].(*entity.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveByKeyOrID indicates an expected call of ResolveByKeyOrID.
func (mr *MockIManageMockRecorder) ResolveByKeyOrID(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveByKeyOrID", reflect.TypeOf((*MockIManage)(nil).ResolveByKeyOrID), ctx, ref)
}

// ListModels mocks base method.
func (m *MockIManage) ListModels(ctx context.Context, req entity.ListModelReq) ([]*entity.Model, int64, bool, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", ctx, req)
	ret0, _ := ret[0].([]*entity.Model)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(int64)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// ListModels indicates an expected call of ListModels.
func (mr *MockIManageMockRecorder) ListModels(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockIManage)(nil).ListModels), ctx, req)
}
