// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/task/service (interfaces: ITaskService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/task_service.go -package=mocks . ITaskService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/coze-dev/coze-loop/backend/modules/observability/domain/task/service"
	gomock "go.uber.org/mock/gomock"
)

// MockITaskService is a mock of ITaskService interface.
type MockITaskService struct {
	ctrl     *gomock.Controller
	recorder *MockITaskServiceMockRecorder
	isgomock struct{}
}

// MockITaskServiceMockRecorder is the mock recorder for MockITaskService.
type MockITaskServiceMockRecorder struct {
	mock *MockITaskService
}

// NewMockITaskService creates a new mock instance.
func NewMockITaskService(ctrl *gomock.Controller) *MockITaskService {
	mock := &MockITaskService{ctrl: ctrl}
	mock.recorder = &MockITaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskService) EXPECT() *MockITaskServiceMockRecorder {
	return m.recorder
}

// CheckTaskName mocks base method.
func (m *MockITaskService) CheckTaskName(ctx context.Context, req *service.CheckTaskNameReq) (*service.CheckTaskNameResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTaskName", ctx, req)
	ret0, _ := ret[0].(*service.CheckTaskNameResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTaskName indicates an expected call of CheckTaskName.
func (mr *MockITaskServiceMockRecorder) CheckTaskName(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTaskName", reflect.TypeOf((*MockITaskService)(nil).CheckTaskName), ctx, req)
}

// CreateTask mocks base method.
func (m *MockITaskService) CreateTask(ctx context.Context, req *service.CreateTaskReq) (*service.CreateTaskResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, req)
	ret0, _ := ret[0].(*service.CreateTaskResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockITaskServiceMockRecorder) CreateTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockITaskService)(nil).CreateTask), ctx, req)
}

// GetTask mocks base method.
func (m *MockITaskService) GetTask(ctx context.Context, req *service.GetTaskReq) (*service.GetTaskResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, req)
	ret0, _ := ret[0].(*service.GetTaskResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockITaskServiceMockRecorder) GetTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockITaskService)(nil).GetTask), ctx, req)
}

// ListTasks mocks base method.
func (m *MockITaskService) ListTasks(ctx context.Context, req *service.ListTasksReq) (*service.ListTasksResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, req)
	ret0, _ := ret[0].(*service.ListTasksResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockITaskServiceMockRecorder) ListTasks(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockITaskService)(nil).ListTasks), ctx, req)
}

// UpdateTask mocks base method.
func (m *MockITaskService) UpdateTask(ctx context.Context, req *service.UpdateTaskReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockITaskServiceMockRecorder) UpdateTask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockITaskService)(nil).UpdateTask), ctx, req)
}
