// Code generated by Validator v0.2.6. DO NOT EDIT.

package trace

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *Trace) IsValid() error {
	if p.Tokens != nil {
		if err := p.Tokens.IsValid(); err != nil {
			return fmt.Errorf("field Tokens not valid, %w", err)
		}
	}
	return nil
}
func (p *TokenCost) IsValid() error {
	return nil
}
