// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameObservabilityTaskRun = "auto_task_run"

// ObservabilityTaskRun Task Run信息
type ObservabilityTaskRun struct {
	ID             int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;comment:TaskRun ID" json:"id"`                                                                              // TaskRun ID
	WorkspaceID    int64     `gorm:"column:workspace_id;type:bigint(20) unsigned;not null;index:idx_workspace_task,priority:1;comment:空间ID" json:"workspace_id"`                              // 空间ID
	TaskID         int64     `gorm:"column:task_id;type:bigint(20) unsigned;not null;index:idx_task_id_status,priority:1;index:idx_workspace_task,priority:2;comment:Task ID" json:"task_id"` // Task ID
	TaskType       string    `gorm:"column:task_type;type:varchar(64);not null;comment:Task类型" json:"task_type"`                                                                              // Task类型
	RunStatus      string    `gorm:"column:run_status;type:varchar(64);not null;index:idx_task_id_status,priority:2;comment:Task Run状态" json:"run_status"`                                    // Task Run状态
	RunDetail      *string   `gorm:"column:run_detail;type:json;comment:Task Run运行状态详情" json:"run_detail"`                                                                                    // Task Run运行状态详情
	BackfillDetail *string   `gorm:"column:backfill_detail;type:json;comment:历史回溯Task Run运行状态详情" json:"backfill_detail"`                                                                      // 历史回溯Task Run运行状态详情
	RunStartAt     time.Time `gorm:"column:run_start_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:任务开始时间" json:"run_start_at"`                                                // 任务开始时间
	RunEndAt       time.Time `gorm:"column:run_end_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:任务结束时间" json:"run_end_at"`                                                    // 任务结束时间
	RunConfig      *string   `gorm:"column:run_config;type:json;comment:相关Run的配置信息" json:"run_config"`                                                                                        // 相关Run的配置信息
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                      // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                      // 更新时间
}

// TableName ObservabilityTaskRun's table name
func (*ObservabilityTaskRun) TableName() string {
	return TableNameObservabilityTaskRun
}
