// Code generated by Validator v0.2.6. DO NOT EDIT.

package metric

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *Metric) IsValid() error {
	return nil
}
func (p *MetricPoint) IsValid() error {
	return nil
}
func (p *Compare) IsValid() error {
	if p.ShiftSeconds != nil {
		if *p.ShiftSeconds <= int64(0) {
			return fmt.Errorf("field ShiftSeconds gt rule failed, current value: %v", *p.ShiftSeconds)
		}
	}
	return nil
}
