// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/repo (interfaces: IColumnExtractConfigRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/column_extract_config.go -package=mocks . IColumnExtractConfigRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/entity"
	repo "github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockIColumnExtractConfigRepo is a mock of IColumnExtractConfigRepo interface.
type MockIColumnExtractConfigRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIColumnExtractConfigRepoMockRecorder
	isgomock struct{}
}

// MockIColumnExtractConfigRepoMockRecorder is the mock recorder for MockIColumnExtractConfigRepo.
type MockIColumnExtractConfigRepoMockRecorder struct {
	mock *MockIColumnExtractConfigRepo
}

// NewMockIColumnExtractConfigRepo creates a new mock instance.
func NewMockIColumnExtractConfigRepo(ctrl *gomock.Controller) *MockIColumnExtractConfigRepo {
	mock := &MockIColumnExtractConfigRepo{ctrl: ctrl}
	mock.recorder = &MockIColumnExtractConfigRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIColumnExtractConfigRepo) EXPECT() *MockIColumnExtractConfigRepoMockRecorder {
	return m.recorder
}

// UpsertColumnExtractConfig mocks base method.
func (m *MockIColumnExtractConfigRepo) UpsertColumnExtractConfig(arg0 context.Context, arg1 *repo.UpsertColumnExtractConfigParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertColumnExtractConfig", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertColumnExtractConfig indicates an expected call of UpsertColumnExtractConfig.
func (mr *MockIColumnExtractConfigRepoMockRecorder) UpsertColumnExtractConfig(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertColumnExtractConfig", reflect.TypeOf((*MockIColumnExtractConfigRepo)(nil).UpsertColumnExtractConfig), arg0, arg1)
}

// GetColumnExtractConfig mocks base method.
func (m *MockIColumnExtractConfigRepo) GetColumnExtractConfig(arg0 context.Context, arg1 repo.GetColumnExtractConfigParam) (*entity.ColumnExtractConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnExtractConfig", arg0, arg1)
	ret0, _ := ret[0].(*entity.ColumnExtractConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetColumnExtractConfig indicates an expected call of GetColumnExtractConfig.
func (mr *MockIColumnExtractConfigRepoMockRecorder) GetColumnExtractConfig(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnExtractConfig", reflect.TypeOf((*MockIColumnExtractConfigRepo)(nil).GetColumnExtractConfig), arg0, arg1)
}

// ListColumnExtractConfigs mocks base method.
func (m *MockIColumnExtractConfigRepo) ListColumnExtractConfigs(arg0 context.Context, arg1 repo.ListColumnExtractConfigParam) ([]*entity.ColumnExtractConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListColumnExtractConfigs", arg0, arg1)
	ret0, _ := ret[0].([]*entity.ColumnExtractConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListColumnExtractConfigs indicates an expected call of ListColumnExtractConfigs.
func (mr *MockIColumnExtractConfigRepoMockRecorder) ListColumnExtractConfigs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListColumnExtractConfigs", reflect.TypeOf((*MockIColumnExtractConfigRepo)(nil).ListColumnExtractConfigs), arg0, arg1)
}
