// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/repo (interfaces: IViewRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/view.go -package=mocks . IViewRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/coze-dev/coze-loop/backend/modules/observability/domain/trace/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockIViewRepo is a mock of IViewRepo interface.
type MockIViewRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIViewRepoMockRecorder
}

// MockIViewRepoMockRecorder is the mock recorder for MockIViewRepo.
type MockIViewRepoMockRecorder struct {
	mock *MockIViewRepo
}

// NewMockIViewRepo creates a new mock instance.
func NewMockIViewRepo(ctrl *gomock.Controller) *MockIViewRepo {
	mock := &MockIViewRepo{ctrl: ctrl}
	mock.recorder = &MockIViewRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIViewRepo) EXPECT() *MockIViewRepoMockRecorder {
	return m.recorder
}

// CreateView mocks base method.
func (m *MockIViewRepo) CreateView(arg0 context.Context, arg1 *entity.ObservabilityView) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateView", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateView indicates an expected call of CreateView.
func (mr *MockIViewRepoMockRecorder) CreateView(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateView", reflect.TypeOf((*MockIViewRepo)(nil).CreateView), arg0, arg1)
}

// DeleteView mocks base method.
func (m *MockIViewRepo) DeleteView(arg0 context.Context, arg1, arg2 int64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteView", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteView indicates an expected call of DeleteView.
func (mr *MockIViewRepoMockRecorder) DeleteView(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteView", reflect.TypeOf((*MockIViewRepo)(nil).DeleteView), arg0, arg1, arg2, arg3)
}

// GetView mocks base method.
func (m *MockIViewRepo) GetView(arg0 context.Context, arg1 int64, arg2 *int64, arg3 *string) (*entity.ObservabilityView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetView", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*entity.ObservabilityView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetView indicates an expected call of GetView.
func (mr *MockIViewRepoMockRecorder) GetView(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetView", reflect.TypeOf((*MockIViewRepo)(nil).GetView), arg0, arg1, arg2, arg3)
}

// ListViews mocks base method.
func (m *MockIViewRepo) ListViews(arg0 context.Context, arg1 int64, arg2 string) ([]*entity.ObservabilityView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListViews", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entity.ObservabilityView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListViews indicates an expected call of ListViews.
func (mr *MockIViewRepoMockRecorder) ListViews(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListViews", reflect.TypeOf((*MockIViewRepo)(nil).ListViews), arg0, arg1, arg2)
}

// UpdateView mocks base method.
func (m *MockIViewRepo) UpdateView(arg0 context.Context, arg1 *entity.ObservabilityView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateView", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateView indicates an expected call of UpdateView.
func (mr *MockIViewRepoMockRecorder) UpdateView(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateView", reflect.TypeOf((*MockIViewRepo)(nil).UpdateView), arg0, arg1)
}
